<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CityHomeServicesFix.Domain\CityHomeServicesFix.Domain.csproj" />
    <ProjectReference Include="..\CityHomeServicesFix.Shared\CityHomeServicesFix.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mappings\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
  </ItemGroup>

</Project>
